[build-system]
requires = [
    "scikit-build-core>=0.10",
]
build-backend = "scikit_build_core.build"

[project]
name = "thrift-compiler"
description = "Thrift binary to compile .thrift files"
version = "0.21.0"
authors = [
    {name = "Adrian Stachlewski", email = "starhel.github@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT AND Apache-2.0"}
keywords = ["thrift", "compiler", "build"]
classifiers = [
    "Development Status :: 3 - Alpha ",
    "Intended Audience :: Developers",
    "Topic :: Utilities"
]

[tool.scikit-build]
minimum-version = "build-system.requires"
wheel.py-api = "py3"
cmake.version = ">=3.25"
cmake.args = ["-G=Unix Makefiles"]

[tool.cibuildwheel]
build-verbosity = 1
test-command = "tox -c {project}/tox.ini -e py3 --installpkg {wheel}"
test-requires = ["tox>=4"]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-i686-image = "manylinux2014"
manylinux-aarch64-image = "manylinux_2_28"

[tool.cibuildwheel.linux.environment]
ACLOCAL_PATH = "/usr/share/aclocal"
CMAKE_BUILD_PARALLEL_LEVEL = "$(nproc)"

[tool.cibuildwheel.macos]
before-all = "brew install autoconf automake libtool bison"

[tool.cibuildwheel.macos.environment]
PATH = "$(brew --prefix bison)/bin:$PATH"
LDFLAGS = "-L$(brew --prefix bison)/lib"
CXXFLAGS = "-Wno-inconsistent-missing-override"
CMAKE_BUILD_PARALLEL_LEVEL = "$(sysctl -n hw.logicalcpu)"
