name: Build

on: [push, pull_request]

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: ./dist/*.tar.gz

  build_wheels:
    name: Build ${{ matrix.build }}${{ matrix.arch }} wheels on ${{ matrix.os }}
    needs: build_sdist
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: "x86_64"
            build: "manylinux_"
            use_qemu: false
          - os: ubuntu-latest
            arch: "x86_64"
            build: "musllinux_"
            use_qemu: false
          - os: ubuntu-latest
            arch: "i686"
            build: "manylinux_"
            use_qemu: false
          - os: ubuntu-latest
            arch: "i686"
            build: "musllinux_"
            use_qemu: false
          - os: ubuntu-latest
            arch: "aarch64"
            build: "manylinux_"
            use_qemu: true
          - os: windows-latest
            arch: "AMD64"
            build: ""
            use_qemu: false
          - os: windows-latest
            arch: "x86"
            build: ""
            use_qemu: false
          - os: macos-13  # macOS / Intel
            arch: "x86_64"
            build: ""
            use_qemu: false
          - os: macos-14  # macOS / Apple Silicon
            arch: "arm64"
            build: ""
            use_qemu: false

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cibw-sdist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        if: matrix.use_qemu

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21
        with:
          package-dir: "$(ls thrift_compiler-*.tar.gz)"
          output-dir: "wheelhouse"
        env:
          CIBW_ARCHS: "${{ matrix.arch }}"
          CIBW_BUILD: "cp313-${{ matrix.build }}*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-${{ matrix.os }}-${{ matrix.build }}${{ matrix.arch }}
          path: ./wheelhouse/*.whl
